### ISSUE TITLE
Releases, tags, dev vs master branch?

### ISSUE THREAD

**Issue by andybak** [dumbgamedev/VRTK_Playmaker3x#1]
It would be great if there was some marker for "here's a stable point. Use this" vs "whatever I last pushed". A lot of projects keep a seperate dev branch and only push to master when it's in a pretty solid state. Or alternatively you could tag some commits with a version number?

**Comment by ericvanderwal** [comment]
Thanks for the comment. Sorry for the slow reply. I have created branches for 3.1.0, 3.20, and now the current master is against VRTK 3.3.0 beta (the current github version of VRTK). I will try and keep better branches for the future.
